import exampleImage from '../../assets/example.jpg'
import exampleImage1 from '../../assets/example1.jpg'
import exampleImage2 from '../../assets/example2.jpg'

export const data = [
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage1,
    name:"Product",
    price:2000
  },
  {
    img:exampleImage2,
    name:"Product",
    price:2000
  },
]